### PR TITLE
Fix to use has("gui_runnig") in an another file

### PR DESCRIPTION
**Pull request by sh8**

### CODE REVIEW

**Comment by sh8** [comment]
Sorry, I totally forgot to modify an another file using`&term` variable.

**Comment by sh8** [comment]
Could you check this PR?

**Comment by callmekohei** [comment]
@sh8 
Hello. Ok. I'll do it later. plaese wait a while. :-)

**Comment by callmekohei** [comment]
@sh8 
Nice ! :-)

**Pull request merged**
